# Generated by Django 6.0.6 on 2026-06-06 08:35

import django.db.models.deletion
from django.db import migrations, models


def migrate_category_texts(apps, schema_editor):
    Category = apps.get_model("api", "Category")
    CategoryTranslation = apps.get_model("api", "CategoryTranslation")
    Language = apps.get_model("localization", "Language")

    default_lang = Language.objects.filter(is_default=True).first()
    if default_lang is None:
        default_lang = Language.objects.filter(code="tr").first()
    if default_lang is None:
        return

    for category in Category.objects.all():
        CategoryTranslation.objects.get_or_create(
            category=category,
            language=default_lang,
            defaults={
                "name": category.name,
                "title": category.title or "",
                "description": category.description or "",
            },
        )


def reverse_migrate_category_texts(apps, schema_editor):
    CategoryTranslation = apps.get_model("api", "CategoryTranslation")
    CategoryTranslation.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_category_options_category_description_and_more'),
        ('localization', '0003_language_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Kategori çevirisi',
                'verbose_name_plural': 'Kategori çevirileri',
            },
        ),
        migrations.AddField(
            model_name='categorytranslation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.category', verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='categorytranslation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_translations', to='localization.language', verbose_name='Dil'),
        ),
        migrations.RunPython(migrate_category_texts, reverse_migrate_category_texts),
        # MySQL FK on parent_id uses the composite unique index; add a standalone index first.
        migrations.RunSQL(
            sql="CREATE INDEX api_category_parent_id_fk_idx ON api_category (parent_id)",
            reverse_sql="DROP INDEX api_category_parent_id_fk_idx ON api_category",
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name_per_parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddConstraint(
            model_name='categorytranslation',
            constraint=models.UniqueConstraint(fields=('category', 'language'), name='unique_category_translation_per_language'),
        ),
    ]
