# Generated by Django 6.0.6 on 2026-06-06 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sync_category_order_from_tree'),
        ('localization', '0004_language_single_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Görsel')),
                ('is_available', models.BooleanField(default=True, verbose_name='Satışta')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Popüler')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kalori')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Ad')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('ingredients', models.TextField(blank=True, verbose_name='İçindekiler')),
                ('allergens', models.TextField(blank=True, verbose_name='Alerjenler')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_translations', to='localization.language', verbose_name='Dil')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün çevirisi',
                'verbose_name_plural': 'Ürün çevirileri',
                'constraints': [models.UniqueConstraint(fields=('product', 'language'), name='unique_product_translation_per_language')],
            },
        ),
    ]
