# Generated by Django 6.0.6 on 2026-06-06 14:55

import api.models
import django.db.models.deletion
from django.db import migrations, models


def seed_site_settings(apps, schema_editor):
    SiteSettings = apps.get_model("api", "SiteSettings")
    SiteSettingsTranslation = apps.get_model("api", "SiteSettingsTranslation")
    Language = apps.get_model("localization", "Language")

    settings, _ = SiteSettings.objects.get_or_create(
        name="Varsayılan",
        defaults={"is_active": True},
    )

    default_lang = Language.objects.filter(is_default=True).first()
    if default_lang is None:
        default_lang = Language.objects.filter(code="tr").first()
    if default_lang is None:
        return

    SiteSettingsTranslation.objects.get_or_create(
        settings=settings,
        language=default_lang,
        defaults={
            "title": "QR Menu",
            "keywords": "qr menu, dijital menü",
            "description": "Dijital restoran menüsü",
            "copyright": "",
        },
    )


def unseed_site_settings(apps, schema_editor):
    SiteSettings = apps.get_model("api", "SiteSettings")
    SiteSettings.objects.filter(name="Varsayılan").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_imagecategory_upload_image"),
        ("localization", "0004_language_single_default"),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Varsayılan', help_text='Yönetim panelinde ayırt etmek için dahili ad.', max_length=100, verbose_name='Site adı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Site ayarı',
                'verbose_name_plural': 'Site ayarları',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.category_image_upload_to, verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.product_image_upload_to, verbose_name='Görsel'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_type', models.CharField(choices=[('phone', 'Telefon'), ('fax', 'Faks'), ('email', 'E-posta'), ('address', 'Adres'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'X (Twitter)'), ('whatsapp', 'WhatsApp'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('website', 'Web sitesi'), ('other', 'Diğer')], max_length=20, verbose_name='Tür')),
                ('label', models.CharField(blank=True, help_text='Örn: Ana hat, Şube, Destek', max_length=100, verbose_name='Etiket')),
                ('value', models.TextField(verbose_name='Değer')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.sitesettings', verbose_name='Site ayarı')),
            ],
            options={
                'verbose_name': 'İletişim',
                'verbose_name_plural': 'İletişim bilgileri',
                'ordering': ['contact_type', 'order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettingsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('keywords', models.TextField(blank=True, verbose_name='Anahtar kelimeler')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('copyright', models.TextField(blank=True, verbose_name='Telif hakkı')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to=api.models.settings_favicon_upload_to, verbose_name='Favicon')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=api.models.settings_logo_upload_to, verbose_name='Logo')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_settings_translations', to='localization.language', verbose_name='Dil')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.sitesettings', verbose_name='Site ayarı')),
            ],
            options={
                'verbose_name': 'Site ayarı çevirisi',
                'verbose_name_plural': 'Site ayarı çevirileri',
                'constraints': [models.UniqueConstraint(fields=('settings', 'language'), name='unique_site_settings_translation_per_language')],
            },
        ),
        migrations.RunPython(seed_site_settings, unseed_site_settings),
    ]
