# Generated by Django 6.0.6 on 2026-06-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_site_settings_and_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['contact_type', 'priority', 'pk'], 'verbose_name': 'İletişim', 'verbose_name_plural': 'İletişim bilgileri'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='order',
        ),
        migrations.AddField(
            model_name='contact',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Aynı türde birden fazla kayıt varsa düşük değer önce gelir.', verbose_name='Öncelik'),
        ),
    ]
