# Generated by Django 6.0.6 on 2026-06-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_contact_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingstranslation',
            name='about_us',
            field=models.TextField(blank=True, verbose_name='Hakkımızda'),
        ),
    ]
