# Generated by Django 6.0.6 on 2026-06-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_sitesettings_about_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettingstranslation',
            name='about_us',
        ),
    ]
