# Generated by Django 6.0.6 on 2026-06-07 11:47

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_sitesettings_about_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecategory',
            name='upload_path',
        ),
        migrations.AddField(
            model_name='imagecategory',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Hedef “Kategori” ise hangi kategori için olduğunu seçin.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_categories', to='api.category', verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='imagecategory',
            name='icon',
            field=models.ImageField(blank=True, help_text='Görsel, images/{kod}/ altına kaydedilir.', null=True, upload_to=api.models.image_category_upload_to, verbose_name='Örnek görsel'),
        ),
        migrations.AddField(
            model_name='imagecategory',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Hedef “Ürün” ise hangi ürün için olduğunu seçin.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_categories', to='api.product', verbose_name='Ürün'),
        ),
        migrations.AddConstraint(
            model_name='imagecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('target', 'category'), name='unique_imagecategory_target_category'),
        ),
        migrations.AddConstraint(
            model_name='imagecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('target', 'product'), name='unique_imagecategory_target_product'),
        ),
    ]
