# Generated by Django 6.0.6 on 2026-06-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_imagecategory_target_links'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='imagecategory',
            name='unique_imagecategory_target_category',
        ),
        migrations.RemoveConstraint(
            model_name='imagecategory',
            name='unique_imagecategory_target_product',
        ),
    ]
