# Generated by Django 6.0.6 on 2026-06-07 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_imagecategory_db_constraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecategory',
            name='target',
        ),
        migrations.AlterField(
            model_name='imagecategory',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Belirli bir kategori için ise seçin.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_categories', to='api.category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='imagecategory',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Belirli bir ürün için ise seçin.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_categories', to='api.product', verbose_name='Ürün'),
        ),
    ]
