# Generated by Django 6.0.6 on 2026-06-07 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_imagecategory_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/products/gallery/', verbose_name='Görsel')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt metin')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='api.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Galeri görseli',
                'verbose_name_plural': 'Galeri görselleri',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
