# Generated by Django 6.0.6 on 2026-06-07 12:03

import api.models
import django.db.models.deletion
from django.db import migrations, models


def migrate_gallery_data(apps, schema_editor):
    ImageGaleri = apps.get_model("api", "ImageGaleri")
    ProductGalleryImage = apps.get_model("api", "ProductGalleryImage")
    CategoryGalleryImage = apps.get_model("api", "CategoryGalleryImage")
    ImageCategory = apps.get_model("api", "ImageCategory")

    for item in ProductGalleryImage.objects.all().iterator():
        ImageGaleri.objects.create(
            product_id=item.product_id,
            image=item.image,
            alt_text=item.alt_text,
            order=item.order,
            is_active=True,
            created_at=item.created_at,
            updated_at=item.updated_at,
        )

    for item in CategoryGalleryImage.objects.all().iterator():
        ImageGaleri.objects.create(
            category_id=item.category_id,
            image=item.image,
            alt_text=item.alt_text,
            order=item.order,
            is_active=True,
            created_at=item.created_at,
            updated_at=item.updated_at,
        )

    for item in ImageCategory.objects.exclude(icon="").exclude(icon__isnull=True).iterator():
        if not item.product_id and not item.category_id:
            continue
        ImageGaleri.objects.create(
            product_id=item.product_id,
            category_id=item.category_id,
            image=item.icon,
            alt_text=item.name or "",
            order=item.order,
            is_active=item.is_active,
            created_at=item.created_at,
            updated_at=item.updated_at,
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_category_gallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageGaleri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to=api.models.image_galeri_upload_to,
                        verbose_name="Görsel",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Alt metin"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="api.category",
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="api.product",
                        verbose_name="Ürün",
                    ),
                ),
            ],
            options={
                "verbose_name": "Görsel galerisi",
                "verbose_name_plural": "Görsel galerileri",
                "ordering": ["order", "pk"],
            },
        ),
        migrations.RunPython(migrate_gallery_data, noop),
        migrations.DeleteModel(
            name="CategoryGalleryImage",
        ),
        migrations.DeleteModel(
            name="ProductGalleryImage",
        ),
        migrations.DeleteModel(
            name="ImageCategory",
        ),
    ]
