# Generated by Django 6.0.6 on 2026-06-07 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_admin_model_menu_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAppMenuOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_label', models.CharField(max_length=100, verbose_name='Uygulama')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_app_menu_orders', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Admin uygulama sırası',
                'verbose_name_plural': 'Admin uygulama sıraları',
                'ordering': ['order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('user', 'app_label'), name='unique_admin_app_menu_order')],
            },
        ),
    ]
