# Generated by Django 6.0.6 on 2026-06-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_admin_app_menu_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingstranslation',
            name='hours_note',
            field=models.TextField(blank=True, help_text='Örn: Bayram günleri ve resmi tatillerde çalışma zamanı değişiklik gösterebilir.', verbose_name='Çalışma saatleri notu'),
        ),
        migrations.AddField(
            model_name='sitesettingstranslation',
            name='weekday_days',
            field=models.CharField(blank=True, help_text='Örn: Pazartesi – Cuma', max_length=200, verbose_name='Çalışma günleri'),
        ),
        migrations.AddField(
            model_name='sitesettingstranslation',
            name='weekday_hours',
            field=models.CharField(blank=True, help_text='Örn: 09:00 – 18:00', max_length=200, verbose_name='Çalışma saatleri'),
        ),
        migrations.AddField(
            model_name='sitesettingstranslation',
            name='weekend_days',
            field=models.CharField(blank=True, help_text='Örn: Cumartesi', max_length=200, verbose_name='Hafta sonu çalışma günleri'),
        ),
        migrations.AddField(
            model_name='sitesettingstranslation',
            name='weekend_hours',
            field=models.CharField(blank=True, help_text='Örn: 10:00 – 16:00', max_length=200, verbose_name='Hafta sonu çalışma saatleri'),
        ),
    ]
