# Generated by Django 6.0.6 on 2026-06-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_site_settings_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingstranslation',
            name='hours_label',
            field=models.CharField(blank=True, help_text='Ön yüzde çalışma saatleri bölümünün başlığı. Örn: Hours, Çalışma Saatleri', max_length=200, verbose_name='Çalışma saatleri başlığı'),
        ),
    ]
