# Generated by Django 6.0.6 on 2026-06-07 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_site_settings_hours_label'),
        ('localization', '0004_language_single_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('starts_at', models.DateTimeField(blank=True, help_text='Boş bırakılırsa hemen geçerli sayılır.', null=True, verbose_name='Başlangıç')),
                ('ends_at', models.DateTimeField(blank=True, help_text='Boş bırakılırsa süresiz geçerlidir.', null=True, verbose_name='Bitiş')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Birden fazla kampanya çakışırsa yüksek değer önce değerlendirilir.', verbose_name='Öncelik')),
                ('products', models.ManyToManyField(blank=True, related_name='campaigns', to='api.product', verbose_name='Kapsanan ürünler')),
            ],
            options={
                'verbose_name': 'Kampanya',
                'verbose_name_plural': 'Kampanyalar',
                'ordering': ['-priority', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_type', models.CharField(choices=[('percentage', 'Ürün indirimi (%)'), ('fixed_amount', 'Sabit tutar indirimi'), ('buy_x_get_y', 'X al Y indirimli / bedava'), ('nth_item', 'N. ürün indirimi')], max_length=20, verbose_name='Kural türü')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Yüzde indirim, N. ürün veya bedava/indirimli ürün için kullanılır.', max_digits=5, null=True, verbose_name='İndirim (%)')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Sabit tutar indirimi için.', max_digits=10, null=True, verbose_name='İndirim tutarı')),
                ('buy_quantity', models.PositiveIntegerField(blank=True, help_text='X al Y kuralları için. Örn: 1 alana 1 bedava → 1', null=True, verbose_name='Alınacak adet (X)')),
                ('reward_quantity', models.PositiveIntegerField(blank=True, help_text='X al Y kuralları için. Genelde 1.', null=True, verbose_name='Kazanılacak adet (Y)')),
                ('item_ordinal', models.PositiveIntegerField(blank=True, help_text='N. ürün indirimi için. Örn: 2 → ikinci ürün, 3 → üçüncü ürün.', null=True, verbose_name='Ürün sırası (N)')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='api.campaign', verbose_name='Kampanya')),
            ],
            options={
                'verbose_name': 'Kampanya kuralı',
                'verbose_name_plural': 'Kampanya kuralları',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CampaignTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Ad')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('badge', models.CharField(blank=True, help_text='Örn: 1+1, %50', max_length=80, verbose_name='Rozet metni')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.campaign', verbose_name='Kampanya')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_translations', to='localization.language', verbose_name='Dil')),
            ],
            options={
                'verbose_name': 'Kampanya çevirisi',
                'verbose_name_plural': 'Kampanya çevirileri',
                'constraints': [models.UniqueConstraint(fields=('campaign', 'language'), name='unique_campaign_translation_per_language')],
            },
        ),
    ]
