# Generated by Django 6.0.6 on 2026-06-08 08:04

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_product_is_popular_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='icon',
            field=models.CharField(blank=True, choices=[('', 'Otomatik (türe göre)'), ('Phone', 'Telefon'), ('Printer', 'Faks'), ('Mail', 'E-posta'), ('MapPin', 'Konum'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Twitter', 'X (Twitter)'), ('MessageCircle', 'WhatsApp'), ('Youtube', 'YouTube'), ('Linkedin', 'LinkedIn'), ('Music', 'TikTok'), ('Globe', 'Web sitesi'), ('Link', 'Diğer')], help_text='Boş bırakılırsa türe göre otomatik seçilir.', max_length=30, verbose_name='İkon'),
        ),
        migrations.CreateModel(
            name='ChefRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.chef_recommendation_image_upload_to, verbose_name='Görsel')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef_recommendations', to='api.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Şefin önerisi',
                'verbose_name_plural': 'Şefin önerileri',
                'ordering': ['-pk'],
            },
        ),
    ]
