# Generated by Django 6.0.6 on 2026-06-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_chef_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefrecommendation',
            name='product',
        ),
        migrations.AddField(
            model_name='chefrecommendation',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='chef_recommendations', to='api.product', verbose_name='Ürünler'),
        ),
    ]
