# Generated by Django 6.0.6 on 2026-06-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_chef_recommendation_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefrecommendationtranslation',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Ön açıklama'),
        ),
    ]
