# Generated by Django 6.0.6 on 2026-06-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_chef_recommendation_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prep_time',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dakika cinsinden.', null=True, verbose_name='Hazırlama Süresi'),
        ),
    ]
