# Generated by Django 6.0.6 on 2026-06-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_product_prep_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefrecommendation',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Deaktif')], default='active', max_length=20, verbose_name='Statü'),
        ),
    ]
