# Generated by Django 6.0.6 on 2026-06-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_chef_recommendation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingstranslation',
            name='description_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Açıklama başlığı'),
        ),
        migrations.AddField(
            model_name='sitesettingstranslation',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Kısa açıklama'),
        ),
    ]
