# Generated by Django 6.0.6 on 2026-06-08 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_site_settings_description_fields'),
        ('localization', '0012_seed_no_dishes_ui_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(choices=[('Award', 'Ödül'), ('Clock', 'Saat'), ('MapPin', 'Konum'), ('Phone', 'Telefon'), ('Mail', 'E-posta'), ('Globe', 'Dünya'), ('Link', 'Bağlantı'), ('Sparkles', 'Parıltı'), ('Heart', 'Kalp'), ('Users', 'Kullanıcılar'), ('Star', 'Yıldız')], default='Award', max_length=30, verbose_name='İkon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='api.sitesettings', verbose_name='Site ayarı')),
            ],
            options={
                'verbose_name': 'Öne çıkan özellik',
                'verbose_name_plural': 'Öne çıkan özellikler',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SiteHighlightTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.sitehighlight', verbose_name='Öne çıkan özellik')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_highlight_translations', to='localization.language', verbose_name='Dil')),
            ],
            options={
                'verbose_name': 'Öne çıkan özellik çevirisi',
                'verbose_name_plural': 'Öne çıkan özellik çevirileri',
                'constraints': [models.UniqueConstraint(fields=('highlight', 'language'), name='unique_site_highlight_translation_per_language')],
            },
        ),
    ]
