# Generated by Django 6.0.6 on 2026-06-11 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_sitesettings_frontend_public_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttemptState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP adresi')),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Basarisiz deneme')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Kilit bitis zamani')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncellendi')),
            ],
            options={
                'verbose_name': 'Giris deneme durumu',
                'verbose_name_plural': 'Giris deneme durumlari',
            },
        ),
        migrations.CreateModel(
            name='SqlInjectionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('forwarded_for', models.TextField(blank=True, verbose_name='X-Forwarded-For')),
                ('country_code', models.CharField(blank=True, max_length=8, verbose_name='Ulke kodu')),
                ('country_name', models.CharField(blank=True, max_length=100, verbose_name='Ulke')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Sehir')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='Bolge')),
                ('location_label', models.CharField(blank=True, max_length=255, verbose_name='Konum ozeti')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('browser_name', models.CharField(blank=True, max_length=80, verbose_name='Tarayici')),
                ('os_name', models.CharField(blank=True, max_length=80, verbose_name='Isletim sistemi')),
                ('device_type', models.CharField(blank=True, max_length=40, verbose_name='Cihaz tipi')),
                ('is_mobile', models.BooleanField(default=False, verbose_name='Mobil')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Bot')),
                ('request_method', models.CharField(blank=True, max_length=16, verbose_name='HTTP metodu')),
                ('request_path', models.CharField(blank=True, max_length=512, verbose_name='Istek yolu')),
                ('query_string', models.TextField(blank=True, verbose_name='Query string')),
                ('request_body', models.TextField(blank=True, verbose_name='Istek govdesi (kisaltilmis)')),
                ('matched_pattern', models.CharField(max_length=255, verbose_name='Eslesen kalip')),
                ('matched_value', models.TextField(blank=True, verbose_name='Eslesen deger (kisaltilmis)')),
                ('source', models.CharField(blank=True, max_length=64, verbose_name='Kaynak alan')),
                ('security_headers', models.JSONField(blank=True, default=dict, verbose_name='Guvenlik basliklari')),
            ],
            options={
                'verbose_name': 'SQL injection girisimi',
                'verbose_name_plural': 'SQL injection girisimleri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='api_sqlinje_created_8e7f86_idx'), models.Index(fields=['ip_address', '-created_at'], name='api_sqlinje_ip_addr_132ec6_idx')],
            },
        ),
        migrations.CreateModel(
            name='FrontendLoginAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('event_type', models.CharField(choices=[('success', 'Basarili giris'), ('failed', 'Basarisiz giris'), ('blocked', 'Kilitli (cok deneme)'), ('forbidden_role', 'Yetkisiz rol'), ('validation_error', 'Eksik alan')], max_length=32, verbose_name='Olay')),
                ('username_attempted', models.CharField(blank=True, max_length=150, verbose_name='Denenen kullanici adi')),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name='Hata nedeni')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('forwarded_for', models.TextField(blank=True, verbose_name='X-Forwarded-For')),
                ('country_code', models.CharField(blank=True, max_length=8, verbose_name='Ulke kodu')),
                ('country_name', models.CharField(blank=True, max_length=100, verbose_name='Ulke')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Sehir')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='Bolge')),
                ('postal_code', models.CharField(blank=True, max_length=32, verbose_name='Posta kodu')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Enlem')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Boylam')),
                ('location_label', models.CharField(blank=True, max_length=255, verbose_name='Konum ozeti')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('browser_name', models.CharField(blank=True, max_length=80, verbose_name='Tarayici')),
                ('browser_version', models.CharField(blank=True, max_length=40, verbose_name='Tarayici surumu')),
                ('os_name', models.CharField(blank=True, max_length=80, verbose_name='Isletim sistemi')),
                ('os_version', models.CharField(blank=True, max_length=40, verbose_name='OS surumu')),
                ('device_type', models.CharField(blank=True, max_length=40, verbose_name='Cihaz tipi')),
                ('device_brand', models.CharField(blank=True, max_length=80, verbose_name='Cihaz markasi')),
                ('device_model', models.CharField(blank=True, max_length=120, verbose_name='Cihaz modeli')),
                ('accept_language', models.CharField(blank=True, max_length=255, verbose_name='Accept-Language')),
                ('referer', models.TextField(blank=True, verbose_name='Referer')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='Host')),
                ('request_method', models.CharField(blank=True, max_length=16, verbose_name='HTTP metodu')),
                ('request_path', models.CharField(blank=True, max_length=512, verbose_name='Istek yolu')),
                ('is_secure', models.BooleanField(default=False, verbose_name='HTTPS')),
                ('is_mobile', models.BooleanField(default=False, verbose_name='Mobil')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Bot')),
                ('security_headers', models.JSONField(blank=True, default=dict, verbose_name='Guvenlik basliklari')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontend_login_audits', to=settings.AUTH_USER_MODEL, verbose_name='Kullanici')),
            ],
            options={
                'verbose_name': 'On yuz giris kaydi',
                'verbose_name_plural': 'On yuz giris kayitlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='api_fronten_created_773e59_idx'), models.Index(fields=['ip_address', '-created_at'], name='api_fronten_ip_addr_a72d4b_idx'), models.Index(fields=['username_attempted', '-created_at'], name='api_fronten_usernam_22f40c_idx')],
            },
        ),
    ]
