# Generated by Django 6.0.6 on 2026-06-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0002_seed_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='flag',
            field=models.ImageField(blank=True, help_text='PNG, JPG, SVG veya WebP. Önerilen boyut: 32x32 px', null=True, upload_to='languages/flags/', verbose_name='Bayrak ikonu'),
        ),
    ]
