# Generated by Django 6.0.6 on 2026-06-12 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('page_path', models.CharField(max_length=512, verbose_name='Sayfa yolu')),
                ('query_string', models.CharField(blank=True, max_length=512, verbose_name='Query string')),
                ('visit_source', models.CharField(choices=[('frontend_route', 'On yuz sayfasi'), ('server_request', 'Sunucu istegi')], default='frontend_route', max_length=32, verbose_name='Kaynak')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('forwarded_for', models.TextField(blank=True, verbose_name='X-Forwarded-For')),
                ('country_code', models.CharField(blank=True, max_length=8, verbose_name='Ulke kodu')),
                ('country_name', models.CharField(blank=True, max_length=100, verbose_name='Ulke')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Sehir')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='Bolge')),
                ('postal_code', models.CharField(blank=True, max_length=32, verbose_name='Posta kodu')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Enlem')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Boylam')),
                ('location_label', models.CharField(blank=True, max_length=255, verbose_name='Konum ozeti')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('browser_name', models.CharField(blank=True, max_length=80, verbose_name='Tarayici')),
                ('browser_version', models.CharField(blank=True, max_length=40, verbose_name='Tarayici surumu')),
                ('os_name', models.CharField(blank=True, max_length=80, verbose_name='Isletim sistemi')),
                ('os_version', models.CharField(blank=True, max_length=40, verbose_name='OS surumu')),
                ('device_type', models.CharField(blank=True, max_length=40, verbose_name='Cihaz tipi')),
                ('device_brand', models.CharField(blank=True, max_length=80, verbose_name='Cihaz markasi')),
                ('device_model', models.CharField(blank=True, max_length=120, verbose_name='Cihaz modeli')),
                ('accept_language', models.CharField(blank=True, max_length=255, verbose_name='Accept-Language')),
                ('referer', models.TextField(blank=True, verbose_name='Referer')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='Host')),
                ('request_method', models.CharField(blank=True, max_length=16, verbose_name='HTTP metodu')),
                ('is_secure', models.BooleanField(default=False, verbose_name='HTTPS')),
                ('is_mobile', models.BooleanField(default=False, verbose_name='Mobil')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Bot')),
                ('security_headers', models.JSONField(blank=True, default=dict, verbose_name='Guvenlik basliklari')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_page_visits', to=settings.AUTH_USER_MODEL, verbose_name='Kullanici')),
            ],
            options={
                'verbose_name': 'Site ziyareti',
                'verbose_name_plural': 'Site ziyaretleri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='security_si_created_265c63_idx'), models.Index(fields=['page_path', '-created_at'], name='security_si_page_pa_fda709_idx'), models.Index(fields=['ip_address', '-created_at'], name='security_si_ip_addr_00e7ea_idx')],
            },
        ),
    ]
