# Generated by Django 6.0.6 on 2026-06-14 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adisyon', '0009_money_two_decimal_truncate'),
        ('security', '0002_site_page_visit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepagevisit',
            name='session_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_visits', to='adisyon.sessionkey', verbose_name='Oturum anahtari'),
        ),
        migrations.AddIndex(
            model_name='sitepagevisit',
            index=models.Index(fields=['session_key', '-created_at'], name='security_si_session_434227_idx'),
        ),
    ]
