# Generated by Django 6.0.6 on 2026-06-14 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_site_page_visit_adisyon(apps, schema_editor):
    SitePageVisit = apps.get_model("security", "SitePageVisit")
    Adisyon = apps.get_model("adisyon", "Adisyon")

    for visit in SitePageVisit.objects.filter(
        session_key__isnull=False,
        adisyon__isnull=True,
    ).iterator():
        adisyon = Adisyon.objects.filter(session_key_id=visit.session_key_id).first()
        if adisyon:
            visit.adisyon_id = adisyon.id
            visit.save(update_fields=["adisyon_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('adisyon', '0010_session_key_policy_concurrent_limit'),
        ('security', '0003_site_page_visit_session_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepagevisit',
            name='adisyon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_visits', to='adisyon.adisyon', verbose_name='Adisyon'),
        ),
        migrations.AddIndex(
            model_name='sitepagevisit',
            index=models.Index(fields=['adisyon', '-created_at'], name='security_si_adisyon_3c89a7_idx'),
        ),
        migrations.RunPython(
            backfill_site_page_visit_adisyon,
            migrations.RunPython.noop,
        ),
    ]
