# Generated by Django 6.0.6 on 2026-06-09 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0043_seed_site_highlights'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionKeyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refresh_duration_minutes', models.PositiveIntegerField(default=120, help_text='Oturum her etkileşimde bu kadar dakika uzatılır (örn. 120 = 2 saat).', verbose_name='Yenilenme süresi (dk)')),
            ],
            options={
                'verbose_name': 'Oturum anahtarı ayarı',
                'verbose_name_plural': 'Oturum anahtarı ayarları',
            },
        ),
        migrations.CreateModel(
            name='SessionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Anahtar')),
                ('refresh_duration_minutes', models.PositiveIntegerField(default=120, help_text='Bu oturum için geçerlilik süresi (dakika).', verbose_name='Yenilenme süresi (dk)')),
                ('last_activity_at', models.DateTimeField(verbose_name='Son etkinlik')),
                ('expires_at', models.DateTimeField(verbose_name='Son geçerlilik')),
            ],
            options={
                'verbose_name': 'Oturum anahtarı',
                'verbose_name_plural': 'Oturum anahtarları',
                'ordering': ['-last_activity_at'],
                'indexes': [models.Index(fields=['key'], name='adisyon_ses_key_ff2583_idx'), models.Index(fields=['expires_at'], name='adisyon_ses_expires_0af532_idx')],
            },
        ),
        migrations.CreateModel(
            name='Adisyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adisyon', to='adisyon.sessionkey', verbose_name='Oturum anahtarı')),
            ],
            options={
                'verbose_name': 'Adisyon',
                'verbose_name_plural': 'Adisyonlar',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AdisyonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('adisyon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='adisyon.adisyon', verbose_name='Adisyon')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adisyon_items', to='api.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Adisyon kalemi',
                'verbose_name_plural': 'Adisyon kalemleri',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['adisyon'], name='adisyon_adi_adisyon_748f1d_idx'), models.Index(fields=['product'], name='adisyon_adi_product_ac61ca_idx')],
                'constraints': [models.UniqueConstraint(fields=('adisyon', 'product'), name='unique_adisyon_product')],
            },
        ),
    ]
