# Generated by Django 6.0.6 on 2026-06-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adisyon', '0001_initial'),
        ('api', '0043_seed_site_highlights'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adisyonitem',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Adisyon ürünü', 'verbose_name_plural': 'Adisyon ürünleri'},
        ),
        migrations.AddField(
            model_name='adisyon',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='adisyons', through='adisyon.AdisyonItem', to='api.product', verbose_name='Ürünler'),
        ),
        migrations.AddField(
            model_name='adisyonitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Adisyondaki görüntüleme sırası.', verbose_name='Sıra'),
        ),
    ]
