# Generated by Django 6.0.6 on 2026-06-09 07:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adisyon', '0002_alter_adisyonitem_options_adisyon_products_and_more'),
        ('currency', '0003_seed_currencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='adisyon',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adisyons', to='currency.currency', verbose_name='Para birimi'),
        ),
        migrations.AddField(
            model_name='adisyon',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Toplam tutar'),
        ),
        migrations.AddField(
            model_name='adisyonitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Birim fiyat × adet (güncel satır tutarı).', max_digits=12, verbose_name='Tutar'),
        ),
        migrations.AddField(
            model_name='adisyonitem',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Ürün adisyona eklendiği andaki para birimi.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adisyon_items', to='currency.currency', verbose_name='Para birimi'),
        ),
        migrations.AddField(
            model_name='adisyonitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ürün adisyona eklendiği andaki birim fiyat.', max_digits=10, verbose_name='Birim fiyat'),
        ),
        migrations.AddField(
            model_name='adisyonitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Satır toplamı (birim fiyat × adet).', max_digits=12, verbose_name='Toplam tutar'),
        ),
    ]
