# Generated by Django 6.0.6 on 2026-06-09 07:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adisyon', '0004_backfill_price_snapshots'),
        ('api', '0043_seed_site_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='adisyon',
            name='discounted_total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='İndirimli toplam tutar'),
        ),
        migrations.AddField(
            model_name='adisyonitem',
            name='campaign_rule',
            field=models.ForeignKey(blank=True, help_text='Ürün eklendiğinde uygulanan kural anlık görüntüsü.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adisyon_items', to='api.campaignrule', verbose_name='Uygulanan kampanya kuralı'),
        ),
        migrations.AddField(
            model_name='adisyonitem',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Kampanya kuralı uygulandığında birim fiyat (ortalama).', max_digits=10, verbose_name='İndirimli birim fiyat'),
        ),
    ]
