# Generated by Django 6.0.6 on 2026-06-09 08:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adisyon', '0007_recalculate_campaign_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adisyon',
            name='discounted_total_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=14, verbose_name='İndirimli toplam tutar'),
        ),
        migrations.AlterField(
            model_name='adisyon',
            name='total_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=14, verbose_name='Toplam tutar'),
        ),
        migrations.AlterField(
            model_name='adisyonitem',
            name='discounted_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Kampanya kuralı uygulandığında birim fiyat (ortalama).', max_digits=14, verbose_name='İndirimli birim fiyat'),
        ),
        migrations.AlterField(
            model_name='adisyonitem',
            name='price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Ürün adisyona eklendiği andaki birim fiyat.', max_digits=14, verbose_name='Birim fiyat'),
        ),
    ]
