# Generated by Django 6.0.6 on 2026-06-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adisyon', '0009_money_two_decimal_truncate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionkeypolicy',
            name='max_concurrent_adisyon_sessions',
            field=models.PositiveIntegerField(blank=True, help_text='Yenilenme süresi içinde adisyona ürün ekleyebilen en fazla aktif oturum sayısı. Boş bırakılırsa sınırsız.', null=True, verbose_name='Eşzamanlı adisyon oturumu limiti'),
        ),
    ]
