# Generated by Django 6.0.6 on 2026-06-06 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0009_producttranslation_tag_json_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='ISO 4217 para birimi kodu (örn: USD, EUR, TRY)', max_length=3, unique=True, verbose_name='Kod')),
                ('name', models.CharField(help_text='Para biriminin tam adı (örn: US Dollar, Euro, Turkish Lira)', max_length=100, verbose_name='Ad')),
                ('symbol', models.CharField(help_text='Para birimi sembolü (örn: $, €, ₺)', max_length=10, verbose_name='Sembol')),
                ('is_active', models.BooleanField(default=True, help_text='Bu para birimi aktif mi?', verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, help_text='Görüntüleme sırası', verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Para Birimi',
                'verbose_name_plural': 'Para Birimleri',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buy_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=15, verbose_name='Alış')),
                ('sell_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=15, verbose_name='Satış')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_currency_exchange_rates', to='currency.currency', verbose_name='Kaynak Para Birimi')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='currency.currency', verbose_name='Hedef Para Birimi')),
            ],
            options={
                'verbose_name': 'Para Birimi Çapraz Kuru',
                'verbose_name_plural': 'Para Birimi Çapraz Kurları',
                'ordering': ['from_currency', 'to_currency'],
            },
        ),
        migrations.AddField(
            model_name='currency',
            name='exchange_rates',
            field=models.ManyToManyField(blank=True, related_name='reverse_exchange_rates', through='currency.CurrencyExchangeRate', through_fields=('from_currency', 'to_currency'), to='currency.currency'),
        ),
        migrations.CreateModel(
            name='ProductCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_currencies', to='currency.currency', verbose_name='Para Birimi')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_currency', to='api.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Para Birimi',
                'verbose_name_plural': 'Ürün Para Birimleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='currencyexchangerate',
            index=models.Index(fields=['from_currency'], name='currency_cu_from_cu_ae3daf_idx'),
        ),
        migrations.AddIndex(
            model_name='currencyexchangerate',
            index=models.Index(fields=['to_currency'], name='currency_cu_to_curr_517672_idx'),
        ),
        migrations.AddConstraint(
            model_name='currencyexchangerate',
            constraint=models.UniqueConstraint(fields=('from_currency', 'to_currency'), name='unique_currency_exchange_pair'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['code'], name='currency_cu_code_876faa_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['is_active'], name='currency_cu_is_acti_aba61f_idx'),
        ),
        migrations.AddIndex(
            model_name='productcurrency',
            index=models.Index(fields=['product'], name='currency_pr_product_6ad974_idx'),
        ),
        migrations.AddIndex(
            model_name='productcurrency',
            index=models.Index(fields=['currency'], name='currency_pr_currenc_f6eb4f_idx'),
        ),
    ]
